config/routes.rb
  # States the RESTful verbs of each page and
  # specifies the source path (URL) of a given
  # page. routes.rb also defines where the
  # user should be redirected to depending on the
  # destination controller and accompanying method

Rails.application.routes.draw do
  resources :contact_us
  get 'home/index'
  devise_for :users
  resources :films

  root 'films#index'
  get 'contact_us', to: 'contact_us#new'
  post 'request_contact_path', to: 'contact_us#request_contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_u.rb
class ContactU < ApplicationRecord

  # Defines the validation constraints of the fields
  # which the user will provide an input to. This includes
  # the use of RegEx for the email field as well as a check
  # to see whether the user has inputted anything

  validates :name, :email, :message, presence: true
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message

end

app/models/film.rb
# Defines the validation constraints of the fields
# which the user will provide an input to. For examaple
# the length of the film must be an integer

class Film < ApplicationRecord
    validates :Film_title, :description, :Length, presence: true

    # validates :Length,    format: { with: /\A\d+\z/, message: "must be an integer." }
end

app/models/home.rb
class Home < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "joseph.kutler@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
# Utilises the 'Devise' gem in order to apply more
# meaningful field validations to the User model.

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :email, :encrypted_password, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/channels/application_cable/channel.rb
module ApplicationCable
  class Channel < ActionCable::Channel::Base
  end
end

app/controllers/channels/application_cable/connection.rb
module ApplicationCable
  class Connection < ActionCable::Connection::Base
  end
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController

  # GET /contact_us
  # GET /contact_us.json
  def index
  end

  # GET /contact_us/1
  # GET /contact_us/1.json
  def show
  end

  # GET /contact_us/new
  def new
  end

  # GET /contact_us/1/edit
  def edit
  end

  # POST /contact_us
  # POST /contact_us.json

  # The following 'def' is used to post the values of the
  # contact form to the mailer without an SMTP server being
  # set up.


  def request_contact

    # Obtains the form values from the "params" hash and the
    # keys match according to the field names
    name = params[:name]
    email = params[:email]
    message = params[:message]

    # This selection statement ensures that an email address is
    # provided and shows an alert if we dont

    if email.blank?
      flash[:notice] = I18n.t('contact.request_contact.email_not_sent')
    else
      # Sends the email by calling the 'contact_email' subroutine
      # and passes the values submitted by the user in the form
    ContactMailer.contact_email(email, name, message).deliver_now

      # Shows the according alert
    flash[:notice] = I18n.t('contact.request_contact.email_sent')
  end
  end
end
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.

app/controllers/films_controller.rb
class FilmsController < ApplicationController

  # Appends a callback before actions take place in order to
  # validate that a user is logged in before allowing certain
  # actions to run

  before_action :set_film, only: [:show, :edit, :update, :destroy]

  # GET /films
  # GET /films.json
  def index
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: t('film_status.created') }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: t('film_status.updated') }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: t('film_status.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:Film_title, :description, :Length, :Review)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home

  end
  
  end

app/helpers/application_helper.rb
# Assists in extracting complex logic out of the views so
# that code may be organised better

module ApplicationHelper

  # Links the user to the overall application
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contact_us/_form.html.erb
  <!-- This 'post' form is used for the contact us page
  in order for the user to be able to submit their
  own review of the movie. This will then call the
  mailer upon the 'Submit' button being clicked.
  I made this form as a partial in order to split the
  contact us page up into more manageable parts
  and allow me to debug and solve the problems that I
  may be having in a more concise manner. -->

<div class="container">
<%= form_tag request_contact_path_path, method: 'post' do %>
  <%= label_tag :name, t('contact_form.name') + ":" %>
  <%= text_field_tag :name, ""%>
  <%= label_tag :email, t('contact_form.email') + ":"%>
  <%= email_field_tag :email, ""%>
  <%= label_tag :message, t('contact_form.user_review') + ":"%>
  <%= text_field_tag :message, "", size: 100 %>
  <%= submit_tag "Submit" %>
  <% end %>
</div>

app/views/contact_us/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%=t('navbar.contact_us')%></h1>


<!-- The meta tags found within the head of the HTML section of the document are used to
encourage best practices by including boilerplate constructs such as allowing for a constant zoom ratio,
and to mention to a use if their browser requires an update to prevent any unwarranted errors -->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><%=t('titles.app_title')%></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="css/contact_us.scss">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
  $("p").on({
    mouseenter: function(){
      $(this).css("background-color", "lightgray");
    },
    mouseleave: function(){
      $(this).css("background-color", "#99c0ff");
    },
    click: function(){
      $(this).css("background-color", "lightyellow");
    }
  });
});
</script>
  </head>

  <body>
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
  </body>

<br>

<p><%= link_to t('contact.contact_us'), new_contact_u_path %></p>

app/views/contact_us/new.html.erb
<h1><%=t('general.form')%></h1>

<%= render 'form', contact_u: @contact_u %>

<%= link_to t('general.back_button'), contact_us_path %>

app/views/contact_us/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%=t('contact_form.name')+ ":"%> </strong>
  <%= @contact_u.name %>
</p>

<p>
  <strong><%=t('contact_form.email')%></strong>
  <%= @contact_u.email %>
</p>

<p>
  <strong><%=t('contact_form.message')%></strong>
  <%= @contact_u.message %>
</p>

<%= link_to t('general.back_button'), contact_us_path %>

app/views/films/_form.html.erb
  <!-- This partial form allows a signed in user to create their own film review
      which includes validation on each field. This is shown as an extension of
      the 'films' page -->

<%= form_with(model: film, local: true) do |form| %>
  <% if film.errors.any? %>

  <!-- If any errors in the user responses to the form appear, the appropriate warning will appear -->
    <div id="error_explanation">
      <h2><%= pluralize(film.errors.count, "error") %> <%=t('general.prohibit_saving')%></h2>

      <ul>
      <% film.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Defines the actual form in which the user will enter data -->

  <div class="field">
    <%= form.label :Film_title %>
    <%= form.text_field :Film_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :Length %>
    <%= form.text_field :Length %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<!-- Allows the signed in user to edit the information written about a given film -->

<h1><%=t('titles.edit_title')%></h1>

<%= render 'form', film: @film %>

<%= link_to t('film_processes.show'), @film %> |
<%= link_to t('general.back_button'), films_path %>

app/views/films/index.html.erb
<p id="notice"><%= notice %></p>
<%=stylesheet_link_tag "application.css"%>

<h1><%=t('titles.home_page_title')%></h1>

<!-- The meta tags found within the head of the HTML section of the document are used to
encourage best practices by including boilerplate constructs such as allowing for a constant zoom ratio,
and to mention to a use if their browser requires an update to prevent any unwarranted errors -->

<table>
  <thead>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><%=t('titles.home_page_title')%></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="css/contact_us.scss">
    <tr>
      <th><%=t('film_info.film_title')%></th>
      <th><%=t('film_info.description')%></th>
      <th><%=t('film_info.length')%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser.
        Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <% @films.each do |film| %>
      <tr>
        <td><%= film.Film_title %></td>
        <td><%= film.description %></td>
        <td><%= film.Length %></td>
        <td><%= link_to t('film_processes.show'), film %></td>

        <!-- Checks to see whether the user has been signed in and if so they are able
            to edit and delete films. If they have not signed in then these options will be hidden -->
        <% if user_signed_in? %>
          <li>
            <td><%= link_to t('film_processes.edit'), edit_film_path(film) %></td>
            <td><%= link_to t('film_processes.delete'), film, method: :delete, data: { confirm: t('general.confirmation') } %></td>
          </li>
        <%end%>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- Allows the user to create a new film review only if they are logged in. Otherwise they are
    only allowed to view the database as it stands -->
<% if user_signed_in? %>
<%= link_to t('general.new_film'), new_film_path %>
<% end %>

app/views/films/new.html.erb
<h1><%=t('titles.film_create')%></h1>

<%= render 'form', film: @film %>

<%= link_to t('general.back_button'), films_path %>

app/views/films/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%=t('film_info.film_title')%></strong>
  <%= @film.Film_title %>
</p>

<p>
  <strong><%=t('film_info.description')%></strong>
  <%= @film.description %>
</p>

<p>
  <strong><%=t('film_info.length')%></strong>
  <%= @film.Length %>
</p>
<% if user_signed_in? %>
  <%= link_to t('film_processes.edit'), edit_film_path(@film) %> |
<%end%>

<%= link_to t('general.back_button'), films_path %>

app/views/layouts/_footer.html.erb
<!-- Defines a consistent footer that will be found on each page.
    This has been defined as a partial so that it can be consistently
    called by the overall application file to apply to all pages-->

<footer>
  <p><%=t('general.footer')%></p>
</footer>

app/views/layouts/_header.html.erb
<!-- Defines a consistent footer that will be found on each page.
    This has been defined as a partial so that it can be consistently
    called by the overall application file to apply to all pages-->

<header>

  <!-- Defines the links that will be contained in the navigation bar that will
      be found in the header of each page to allow for ease of access between
      pages -->
  <nav class="navbar navbar-light bg-light">
    <ul>
      <li>
        <%= link_to(t('navbar.home'),root_path)%>
        <!-- If the user is not yet signed in, they should be presented with the
            options to sign in to a current account or sign up for a new account -->
      <% if !user_signed_in? %>
     <li> <%= link_to(t('navbar.sign_up'),new_user_registration_path)%></li>
     <li><%= link_to(t('navbar.sign_in'),new_user_session_path)%></li>
     <% end %>
     <li><%= link_to(t('navbar.contact_us'),contact_us_path)%></li>

     <!-- If the current session involves a user that has signed in, they should
          be presented with the option to logout of their account. If this is
          selected then the current session should be successfully destroyed. -->
     <% if user_signed_in? %>
       <li>
     <%= link_to(t('navbar.sign_out'), destroy_user_session_path, method: :delete) %>
     </li>
     <%end%>
   </ul>

</nav>
<% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
<% end %>
</header>

app/views/layouts/application.html.erb
<!-- This contains the overall code that will be applied consistently across the
    entire site and all associated pages -->

<!DOCTYPE html>
<html>
  <head>
    <title><%=t('titles.app_title')%></title>
    <!-- This line allows for a consistent zoom across all pages -->
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag :modernizr %>
    <%= javascript_include_tag "application" %>
  </head>
  <!-- Includes the header partial across all pages -->
<%= render "layouts/header" %>
  <body>
    <!-- Provides the permissions for all pages to be able to show 'flash' messages
        and notices to the user -->
    <% flash.each do |key, value| %>
  <%= content_tag :div, content_tag(:p, value), id: "#{key}" unless value.blank? %>
  <%end%>
    <%= yield %>
    <!-- Includes the footer partial across all pages -->
  <%= render "layouts/footer" %>

  </body>
</html>